server:
  port: 9000
spring:
  application:
    name: group-service
  datasource:
    url: jdbc:mysql://localhost:3306/qq-group?setUnicode=true&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: Hwb123--
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qq.group.infrastructure.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
